name: Create .env file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  create-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "TEST_SDK_KEY=${{ secrets.TEST_SDK_KEY }}" >> .env
          # Add more environment variables as needed

      - name: Use .env file in subsequent steps
        run: |
          echo "The .env file has been created and can be used in subsequent steps"
          # Example: Run tests using the environment variables
          # npm run test

      # Add more steps here that might need the .env file
      # For example, deployment steps, testing, etc.
